name: Azure Utilities

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/azure/**'

env:
  solutionFolder: 'src/azure'
  buildConfiguration: 'Release'

permissions:
  contents: read
  actions: read
  checks: write
  packages: write

jobs:
  build:
    name: Build and Pack
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Set Build Number
        run: |
          echo "BUILD_NUMBER=$((3000+${{ github.run_number }}))" >> "${{ github.env }}"

      - name: Restore dependencies
        run: dotnet restore ${{ env.solutionFolder }}

      - name: Build
        run: dotnet build ${{ env.solutionFolder }} --no-restore --configuration ${{ env.buildConfiguration }} /p:ContinuousIntegrationBuild=true /p:BuildNumber=${{ env.BUILD_NUMBER }}

      - name: Test
        run: dotnet test ${{ env.solutionFolder }} --no-restore --no-build --configuration ${{ env.buildConfiguration }} --logger "trx;LogFileName=test_results.trx" --results-directory "TestResults"

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: 'TestResults/**/*.trx'
          reporter: dotnet-trx
          fail-on-error: true

      - name: Pack
        run: dotnet pack ${{ env.solutionFolder }} --no-restore --no-build --configuration ${{ env.buildConfiguration }} --output ${{ github.workspace }}/artifacts /p:ContinuousIntegrationBuild=true /p:BuildNumber=${{ env.BUILD_NUMBER }}

      - name: Publish packages
        uses: actions/upload-artifact@v4
        with:
          name: NuGet Packages
          path: ${{ github.workspace }}/artifacts/*.nupkg
